function synthExtract(path, type)
% Get the result form the controller synthesized and then extract the controller coefficients
%
% Function: synthExtract(path, type)
% 
% path: path with the log file generated by synthesis
% type: 'ss' for state-space or 'tf' for transfer-fuction;
%
% Author: Lennon Chaves
% 
% March 2017
%

logfile = 'system_bound_simple.log';

if (strcmp(type, 'tf'))
 command = ['sh dssynth-extract.sh ' logfile];
elseif (strcmp(type, 'ss')) %TODO: Implement shell script to extract for state-space
 command = ['sh dssynth-extract.sh ' logfile];
end 

system(command);

end
