function synthExtract(path, type)
% Get the result form the controller synthesized and then extract the controller coefficients
%
% Function: synthExtract(path, type)
% 
% path: path with the log file generated by synthesis
% type: 'ss' for state-space or 'tf' for transfer-function;
%
% Author: Lennon Chaves
% 
% March 2017
%

if (strcmp(type, 'tf'))
 logfile = 'system_bound_simple.log';
 command = ['sh dssynth-tf-extract.sh ' logfile];
elseif (strcmp(type, 'ss'))
 logfile = 'system_completeness-threshold-ss.log';
 command = ['sh dssynth-ss-extract.sh ' logfile];
end 

system(command);

end
